### ISSUE TITLE
Angular View and Controller for Blog duplicated at app

### ISSUE THREAD

**Issue by brunobertechini** [aspnetboilerplate/sample-blog-module#1]
Hello there,

As per my understanding the module (Blog) would be a completely decoupled from the application (MyAbpZeroProject).

But I can see a blog.cshtml and blog.js files under main app Project.

Is this by design ? 

I mean, Should the view and controller lie on module or app(host) solution ?

Bruno

**Comment by hikalkan** [comment]
Hi,

cshtml and js files are under module project actually: https://github.com/aspnetboilerplate/sample-blog-module/tree/master/src/Abp.Samples.Blog.Web/App/Main/views/blog

But when you install Abp.Samples.Blog.Web nuget package, these files are copied into the application. When we upgrade nuget package, they will be ugraded (so, we shouldn't make changes on these files in the application).

We may think to embed these files into dll, so user can not change them at all. But this causes additional compexity (we should write some special Http handler to get these files from dll, also write a view engine.. etc). I wanted to keep it simple.

**Comment by brunobertechini** [comment]
Thanks I understand the approach.

Would you mind to share the nuget config file for generating the packages ? We would like to apply the same approach

Best Regards

Bruno

**Comment by brunobertechini** [comment]
By the way, would you recommend posting questions to aspnetzero or abp fórum instead of GitHub for questions like this ?

Bruno

**Comment by hikalkan** [comment]
Hi,

This is nuhet packaging batch: https://github.com/aspnetboilerplate/sample-blog-module/blob/master/nupkg/pack_blog_modules.bat

Every project has it's own nuspec. Example: https://github.com/aspnetboilerplate/sample-blog-module/blob/master/src/Abp.Samples.Blog.Web/Abp.Samples.Blog.Web.nuspec

**Comment by hikalkan** [comment]
Yes, please post questions to the forum and bugs/feature-requests here.

Thanks

**Comment by brunobertechini** [comment]
Okay I will use this behavior for now on.

Just to finish this question, regarding the copy of cshtml and js files to web projects, I couldnt find any specific configuration on nuspec file or the bat file.

Can you please point me out how can we achieve this ?

I have both files on my module web Project and would like to copy to same structure when the nuget package is installed into the "app" web Project.

Cheers

Bruno

**Comment by hikalkan** [comment]
No configuration is needed. Nuget automatically does it when it's Build Action is 'Content'.
