### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by Quirt** [aspnetboilerplate/sample-blog-module#4]
Perhaps I'm missing something, but when I run this application, I see the "Blog" entry in the menu, but it does not take me to an admin interface.  It takes me only to a short view of a couple sample posts, and only titles without the ability to click and see samples in their entirety.  Am I missing something?

**Comment by hikalkan** [comment]
You are not missing something. This is just to give an idea of modularity. I believe, adding developing admin interface is straightforward then.
