### ISSUE TITLE
Blog Module update-database issue

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/sample-blog-module#5]
Dear Halil,

i did the following steps to test modularity before i apply it on my work.
i downloaded the sample blog module source code, then changed target framework and updated abp pachages to latest version.
i created new solution from your template and added blog module assembly references and module dependence as you suggest.  
 
i  run the following lines from command prompt to migrate database
1- Migrate Main Application
```dos
migrate.exe TestModularity.EntityFramework.dll /connectionString="Server=.\sqlexpress; Database=TestModularity; User Id=sa;Password=123;" /connectionProviderName="System.Data.SqlClient"
```
2- Migrate Blog Module
```dos
migrate.exe Abp.Samples.Blog.EntityFramework.dll /connectionString="Server=.\sqlexpress; Database=TestModularity; User Id=sa;Password=123;" /connectionProviderName="System.Data.SqlClient"
```
i got an error as you see in the picture, when i check the database i see blog modules tables created, but no data because the error occured befor running seed method
<img width="710" alt="migration" src="https://cloud.githubusercontent.com/assets/6557160/14295077/68dcc8d6-fb74-11e5-9b1f-bc98a6247762.PNG">

What i do wrong ?

**Comment by hikalkan** [comment]
You should run add-migration since when you upgrade abp packages, probably you got new schema changes.

**Comment by emaish** [comment]
This is strange!!!  when i ran add-migration in blog module solution, it tries to generate all abp tables again, but it's already exists it database.
```dos
add-migration test -ConnectionString "Server=.\sqlexpress; Database=TestModularity; User Id=sa;Password=123;" -ConnectionProviderName "System.Data.SqlClient" -ProjectName "Abp.Samples.Blog.EntityFramework"
```
Why it doesn't see the already existing table

**Comment by hikalkan** [comment]
You can delete migration code for blog module like that: https://github.com/aspnetboilerplate/sample-blog-module/blob/master/src/Abp.Samples.Blog.EntityFramework/Migrations/201602171451570_Upgraded_To_Module_Zero_0_8.cs
It probably comes from base dbcontext.

**Comment by emaish** [comment]
Thank you for this work around :), but are you planing to make a configuration or anything that will disable migration for abp Tables ?

**Comment by hikalkan** [comment]
I could not find a way, because it is derived from AbpZeroDbContext which defines base entities.

**Comment by emaish** [comment]
I can live with that :), but i can't understand why clearing the migration file solved the issue ?

**Comment by hikalkan** [comment]
It's related to EF's migration system. It compares model wiith migration hash.. a little long topic. I can suggest you to read about EF migrations. For example, this is a good document: https://msdn.microsoft.com/en-us/data/dn481501.aspx?f=255&MSPPError=-2147217396

**Comment by emaish** [comment]
Thank you Halil :)
