### ISSUE TITLE
Why we use virtual keyword for all the properties instead only for navigational properties?

### ISSUE THREAD

**Issue by JoCodes** [aspnetboilerplate/sample-blog-module#8]
Hi,
Usually , we use virtual properties for navigational properties only ( for lazy load and proxy bind ). But here in this sample all the properties are virtual . May I know the reason behind it.

Thanks.

**Comment by ismcagdas** [comment]
Hi @JoCodes , it is an habit from NHibernate, you can delete those if you like.
